namespace AgentSessionExample.Models;

/// <summary>
/// Represents an agent conversation session containing multiple messages.
/// This is the raw domain model before adaptation for search indexing.
/// </summary>
/// <remarks>
/// <para>
/// Sessions typically capture a complete interaction between a user and an AI agent,
/// including:
/// - The sequence of messages exchanged
/// - Metadata about the session (project, agent type, etc.)
/// - Timestamps for temporal analysis
/// </para>
/// <para>
/// This model is intentionally simple. In production, you might have additional fields like:
/// - User ID
/// - Cost/token usage
/// - Feedback/ratings
/// - Tags/labels
/// </para>
/// </remarks>
public sealed record Session
{
    /// <summary>
    /// Unique identifier for this session.
    /// </summary>
    public required string Id { get; init; }

    /// <summary>
    /// Type of agent that handled this session.
    /// Examples: "code-assistant", "research-agent", "support-bot"
    /// </summary>
    public required string AgentType { get; init; }

    /// <summary>
    /// The project or workspace this session was associated with.
    /// </summary>
    public required string ProjectPath { get; init; }

    /// <summary>
    /// When the session started.
    /// </summary>
    public required DateTime StartedAt { get; init; }

    /// <summary>
    /// When the session ended (if completed).
    /// </summary>
    public DateTime? EndedAt { get; init; }

    /// <summary>
    /// Whether the session is still active.
    /// </summary>
    public bool IsActive { get; init; }

    /// <summary>
    /// Summary or title for this session.
    /// Often generated by summarizing the first message or key topics.
    /// </summary>
    public string? Summary { get; init; }

    /// <summary>
    /// The messages in this session, in chronological order.
    /// </summary>
    public required List<Message> Messages { get; init; }

    /// <summary>
    /// Gets the total message count.
    /// </summary>
    public int MessageCount => Messages.Count;

    /// <summary>
    /// Gets the duration of the session.
    /// </summary>
    public TimeSpan? Duration => EndedAt.HasValue ? EndedAt.Value - StartedAt : null;
}
